### ISSUE TITLE
Bug Report : Data loaded but not displayed

### ISSUE THREAD

**Issue by dayxhep** [ceolter/ag-grid-vue#3]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Datas do not display, the "Loading..." is still there.
Error or Warning in console : none
Error or Warning while compiling : none

**Expected behavior**
The datas should just been displayed.
The headers works perfectly and display as usual.

**Minimal reproduction of the problem with instructions**
Create VueJS app, use a method with an Axios return.
The Grid is fully created and displays the "Loading" when mounted.
The method created is called changing `this.gridOptions` with an array of objects returned by Axios.
At the begin of the method :

`console.log(arr)` outputs:
```
(128) [Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object…]
```
Then :
`this.gridOptions = arr`

But nothing seems to be loaded, i tried to splice(0, 10) thinking the array may be too big.

**Environment:**
Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
Nginx
Npm 3.10.10
Node v6.9.5

* **ag-grid-vue version:** ag-grid-vue@10.0.0

* **VueJS version:** 2.8.1

* **Browser:** All

* **Language:** ES6/7

**Comment by seanlandsman** [comment]
It looks like you're trying to set the row data onto the gridOptions - this is not how you configure ag-Grid

Please refer to the documentation here https://www.ag-grid.com/best-vuejs-data-grid/ for how to use and configure ag-Grid and vue
